DROP TABLE FACT_HISTORY CASCADE;

CREATE TABLE FACT_HISTORY (
     ID_FACT INT NOT NULL,
     ID_PACK INT NOT NULL,
     FACT_NAME VARCHAR(100),
     FACT_DATE DATE,
     FACT_VALUE DECIMAL(10,2),
     PRIMARY KEY (ID_FACT, ID_PACK)
);

