DROP TABLE FACT_HISTORY CASCADE;
DROP TABLE TMP_FACT_HISTORY_COMPARE_DIFF CASCADE;

CREATE TABLE FACT_HISTORY (
     ID_FACT INT NOT NULL,
     ID_PACK INT NOT NULL,
     FACT_NAME VARCHAR(100),
     FACT_DATE DATE,
     FACT_VALUE DECIMAL(10,2),
     PRIMARY KEY (ID_FACT, ID_PACK)
);

CREATE TABLE TMP_FACT_HISTORY_COMPARE_DIFF (
     ID_FACT       NUMBER      NOT NULL,
     COL_NAME      VARCHAR2(100) NOT NULL,
     COL_TYPE      VARCHAR2(30)  NOT NULL,
     COL_OLD_VALUE VARCHAR2(4000),
     COL_NEW_VALUE VARCHAR2(4000)
);

COMMIT;