DROP TABLE BOOKING_HISTORY CASCADE;
DROP TABLE BOOKING CASCADE;

CREATE TABLE BOOKING_HISTORY (
     idr     VARCHAR2(36),
     pesel   VARCHAR2(11),
     ts      DATE DEFAULT SYSDATE,
     status  NUMBER
);

CREATE TABLE BOOKING (
     idr     VARCHAR2(36) PRIMARY KEY,
     pesel   VARCHAR2(11),
     ts      DATE DEFAULT SYSDATE
);

COMMIT;